apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: book-frontend:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 80    # nginx default port

---
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
spec:
  type: NodePort
  selector:
    app: frontend
  ports:
    - port: 80                # Service port exposed externally
      targetPort: 80          # Port inside the container (nginx)
      nodePort: 30080         # NodePort for minikube access
